language: python

python:
  - 3.7

git:
  depth: false
 
dist: xenial

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry install -v

script: pytest