language: python

python:
  - 3.7

git:
  depth: false
 
dist: bionic

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry --version

install:
  - poetry update -vv
  - poetry show -v

before_script:
  - pytest --version
  - flake8 --version
  - black --version

script: 
  - pytest -v
  - flake8 --count
  - black ./ --check